### ISSUE TITLE
Visualization Code/Libraries

### ISSUE THREAD

**Issue by sheshap** [mlvlab/SageMix#1]
Dear Authors,

Congratulations on the NeurIPS paper.
Thank you for releasing the code.

Very nice visualizations.
Can you please release the visualization code/libraries used for visualization?

Thanks in advance.

**Comment by LSanghyeok** [comment]
Hi @sheshap,

Thanks for your interest.
Currently, I don't have the plan to release visualization.
If you want to get similar results, I recommend using PyVista for visualization.
