### ISSUE TITLE
Seeking the correct method to download the 'scanobjectnn' dataset

### ISSUE THREAD

**Issue by wangxin-fighting** [mlvlab/SageMix#3]
Dear author, may I ask if it is convenient for you to provide the "scanobjectnn" dataset? I was unable to successfully download it online and attempted to download it using the "main. py" file you mentioned. In the end, I successfully downloaded a file related to the dataset named "h5_files. zip. 1". However, I am not sure how to handle this dataset in the future. Can you provide any guidance? Thank you in advance for taking the time to review my questions!

**Comment by wangxin-fighting** [comment]
Okay, thank you for your email reply. I saw that your paper mentioned using MN40 for visualization. Could you please provide your visualization code? Thank you.

**Comment by LSanghyeok** [comment]
Hi @wangxin-fighting!

In our experiments, we provide the download links for ScanObjectNN in data.py (https://download.cs.stanford.edu/orion/scanobjectnn/h5_files.zip), which is automatically downloaded during main.py.
We have used two variants of ScanObjectNN (e.g., OBJ_ONLY (main_split_nobg in h5_files.zip), PB_T50_RS (main_split in h5_files.zip)).
Please refer to the original paper and official repository for more detailed information about other variants of ScanObjectNN.

Arxiv for SONN: https://arxiv.org/pdf/1908.04616.pdf
Github for SONN: https://github.com/hkust-vgd/scanobjectnn
