### ISSUE TITLE
pretrained models and how to visualize the point clouds that have been data enhanced after training?

### ISSUE THREAD

**Issue by wangxin-fighting** [mlvlab/SageMix#4]
Hello, author. I have a question that I would like to ask you.
I found that the source code provided by the author on the "github" website does not seem to have the pretrained models of dgcnn and pointnet. Do we need to download it ourselves from other places? Another question is how do we view the visualization of point clouds that have been data enhanced after training?
Looking forward to your reply, thank you!

**Comment by LSanghyeok** [comment]
Hi @wangxin-fighting!

Unfortunately, the checkpoints and the visualization code are unavailable now after data migration. 
Instead, note that we've used PyVista (https://docs.pyvista.org/) for all visualizations.
