### ISSUE TITLE
Is there something wrong with pointnet's network structure?

### ISSUE THREAD

**Issue by tangsankou** [mlvlab/SageMix#5]
![image](https://github.com/mlvlab/SageMix/assets/62491429/84c79fc6-08f9-4471-8942-211475a99d42)
When I ran the training code on pointnet, the following error occurred. Then I went to look at the pointnet code and found that it was not the same structure as I was familiar with before. So could you give me some help, like explain something? ,Many thanks!

**Comment by LSanghyeok** [comment]
Hi @tangsankou!

Sorry for the late reply.

While we report the results in the paper with the official code of PointNet and PointNet++, the current version of PointNet is the PyTorch implementation at https://github.com/antao97/dgcnn.pytorch/tree/master, which may slightly differ in details.

Please refer to the link for the details about it.
